language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t arod7ayee/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arod7ayee/docker-react npm run test